image: Visual Studio 2017
configuration : Release

environment:
  nodejs_version: "8"
  
before_build:
  - nuget restore
  - dotnet restore
  - dotnet build

  
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  
build:
  verbosity: minimal
  publish_wap: true

test_script:
  - dotnet restore
  - dotnet ef migrations add InitialCreate --startup-project "C:\projects\dubbing-backend\web"
  - dotnet ef database update --startup-project "C:\projects\dubbing-backend\Administration/Infrastructure/"
  - dotnet run
