image: Visual Studio 2017

before_build:
  - nuget restore
  - dotnet restore
  - dotnet build
  
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  
build:
  verbosity: minimal
  publish_wap: true


