image: Visual Studio 2017
configuration : 
  - Debug
  - Release
  
matrix: 
  fast_finish: false
  
platform:
  - x64
  - x86
  
environment:
  nodejs_version: "8"
  matrix: 
    - TOOLCHAIN: msv15
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  
before_build:
  - nuget restore
  - dotnet restore
  - dotnet ef migrations add InitialCreate --startup-project "C:\projects\dubbing-backend\web"
  - dotnet ef database update InitialCreate
  - dotnet build
  - dotnet run
  
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  
build:
  verbosity: minimal
  publish_wap: true


